get:
  tags:
    - Training
  summary: Get training session by ID
  description: |
    Retrieve a specific training session by its ID.
  operationId: getTrainingSessionById
  security:
    - BearerAuth: []
  parameters:
    - name: session_id
      in: path
      required: true
      description: ID of the training session to retrieve
      schema:
        type: string
        format: cuid
  responses:
    "200":
      description: Training session with optional attendance sheets
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../../components/schemas/training_session.yaml"
              - type: object
                properties:
                  attendance_sheets:
                    type: array
                    items:
                      $ref: "../../components/schemas/attendance_sheets.yaml"
                    description: "Attendance records for this session (when requested)."
          example:
            id: "clhsession01"
            training_id: "clhtraining01"
            session_date: "2024-02-15"
            location: "Douala Training Center"
            trainer_id: "clhtrainer01"
            max_participants: 30
            status: "scheduled"
            created_at: "2024-02-09T10:00:00Z"
            updated_at: "2024-02-09T10:00:00Z"
            attendance_sheets:
              - id: "clhatt001"
                training_session_id: "clhsession01"
                participant_id: "clhuser01"
                attended_at: "2024-02-15T09:00:00Z"
                notes: "On time"
                created_at: "2024-02-15T09:00:00Z"
                updated_at: "2024-02-15T09:00:00Z"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "429":
      $ref: "../../components/responses/RateLimitError.yaml"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

put:
  tags:
    - Training
  summary: Update a training session
  description: Update an existing training session
  operationId: updateTrainingSession
  security:
    - BearerAuth: []
  parameters:
    - name: session_id
      in: path
      required: true
      description: ID of the training session to update
      schema:
        type: string
        format: cuid
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/training_session.yaml"
  responses:
    "200":
      description: Training session updated successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/training_session.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training session not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Session Not Found"
              message:
                type: string
                example: "Training session with the specified ID was not found"
              code:
                type: string
                example: "TRAINING_SESSION_NOT_FOUND"
    "409":
      description: Update conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Update Conflict"
              message:
                type: string
                example: "Cannot update training session in current state"
              code:
                type: string
                example: "UPDATE_CONFLICT"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

delete:
  tags:
    - Training
  summary: Delete a training session
  description: Delete an existing training session
  operationId: deleteTrainingSession
  security:
    - BearerAuth: []
  parameters:
    - name: session_id
      in: path
      required: true
      description: ID of the training session to delete
      schema:
        type: string
        format: cuid
  responses:
    "204":
      description: Training session deleted successfully
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Training session not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Training Session Not Found"
              message:
                type: string
                example: "Training session with the specified ID was not found"
              code:
                type: string
                example: "TRAINING_SESSION_NOT_FOUND"
    "500":
      $ref: "../../components/responses/ServerError.yaml"
