# List all projects
get:
  tags:
    - Projects
  summary: Get all projects
  description: Retrieve all projects with optional filtering
  operationId: getAllProjects
  security:
    - BearerAuth: []
  parameters:
    - name: company_id
      in: query
      description: company id
      required: false
      schema:
        type: string
        example: AQA9CNo0cXNLt6sZp5Uc5P0
      style: simple
    - in: query
      name: archived
      description: archived projects
      required: false
      schema:
        type: boolean
        example: true
      style: simple
    - in: query
      name: type
      description: The project type to filter the projects by their type.
      required: false
      schema:
        type: string
        example: "initial inspection, external inspection, auto evaluation"
    - in: query
      name: active
      description: active projects
      required: false
      schema:
        type: boolean
        example: true
      style: simple
    - name: draft
      in: query
      description: draft projects
      required: false
      schema:
        type: boolean
        example: true
      style: simple
    - name: skip
      in: query
      description: number of items to skip
      required: true
      schema:
        type: integer
        format: int32
    - name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    "200":
      description: List of projects retrieved successfully
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../components/schemas/project.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Projects not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Not Found"
              message:
                type: string
                example: "No projects found"
    "500":
      $ref: "../../components/responses/ServerError.yaml"

# Create a new project
post:
  tags:
    - Projects
  summary: Create a new project
  description: To create the project form by a specific company administrator (ADG).
  operationId: createProject
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../components/schemas/project.yaml"
        example:
          type: "INITIAL_INSPECTION"
          company_id: "AQA9CNo0cXNLt6sZp5Uc5P0"
          title: "Internal Inspection Project"
          description: "Comprehensive internal inspection for quality assurance"
          sector_activity: "engineering"
          country: "Cameroon"
          city: "Douala"
          status: "DRAFT"
          start_date: "2024-01-01T00:00:00.000Z"
          end_date: "2024-12-31T00:00:00.000Z"
  responses:
    "201":
      description: Project created successfully
      content:
        application/json:
          schema:
            $ref: "../../components/schemas/project.yaml"
    "400":
      $ref: "../../components/responses/ValidationError.yaml"
    "401":
      $ref: "../../components/responses/UnauthorizedError.yaml"
    "403":
      $ref: "../../components/responses/ForbiddenError.yaml"
    "404":
      description: Project not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Not Found"
              message:
                type: string
                example: "Project could not be created"
    "500":
      $ref: "../../components/responses/ServerError.yaml"
